# Generated by Django 4.1 on 2022-09-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_follower_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-timestamp',)},
        ),
    ]
