# Generated by Django 4.1 on 2022-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
